name = 'singularity'
license = 'MIT'
licenselink = 'https://github.com/ezioleq/singularity/blob/master/LICENSE'
description = 'Simple, fast, pretending to be flat and modern theme'

homepage = 'https://github.com/ezioleq/singularity'

tags = ['blog']
features = ['some', 'awesome', 'features']

[author]
  name = 'ezioleq'
  homepage = 'https://ezioleq.com'
